export default {
    LOAD_PARTICIPANTS_REQUESTED: 'app/deployment/LOAD_PARTICIPANTS_REQUESTED',
    LOAD_PARTICIPANTS_SUCCESS: 'app/deployment/LOAD_PARTICIPANTS_SUCCESS',
    LOAD_PARTICIPANTS_ERROR: 'app/deployment/LOAD_PARTICIPANTS_ERROR'
};