export default {
    LOAD_PARTICIPANTS_REQUESTED: "app/participants/LOAD_PARTICIPANTS_REQUESTED",
    LOAD_PARTICIPANTS_SUCCESS: "app/participants/LOAD_PARTICIPANTS_SUCCESS",
    LOAD_PARTICIPANTS_ERROR: "app/participants/LOAD_PARTICIPANTS_ERROR"
};