export default {
    DEPLOYMENTS_DATA_REQUESTED: 'app/deployment/DEPLOYMENTS_DATA_REQUESTED',
    DEPLOYMENTS_DATA_SUCCESSFUL: 'app/deployment/DEPLOYMENTS_DATA_SUCCESSFUL',
    SET_SELECTED_DEPLOYMENT_ID: 'app/deployment/SET_SELECTED_DEPLOYMENT_ID'
};