#! /bin/bash

set -x
export IS_DOCKER=true

# Make sure that node-modules is up to date with package.json
yarn

# Make sure that if yarn has been run outside the container, that node is fixed so that it will run inside the container
#  Sass has a binary component that cannot be shared between Mac and Linux
# npm rebuild node-sass

# Start the dev server after compiling the code.  When this exits, the container will end
yarn run start
