export default {
    USER_DATA_FETCH_REQUESTED: 'app/user/USER_DATA_FETCH_REQUESTED',
    USER_DATA_FETCH_SUCCESSFUL: 'app/user/USER_DATA_FETCH_SUCCESSFUL',
    USER_DATA_FETCH_FAILED: 'app/user/USER_DATA_FETCH_FAILED',
};