export default {
    PARTICIPANT_DATA_FETCH_REQUESTED: 'app/participant/PARTICIPANT_DATA_FETCH_REQUESTED',
    PARTICIPANT_DATA_FETCH_SUCCESSFUL: 'app/participant/PARTICIPANT_DATA_FETCH_SUCCESSFUL',
    PARTICIPANT_DATA_FETCH_FAILED: 'app/participant/PARTICIPANT_DATA_FETCH_FAILED',
};